import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { audit, requirePermission } from "@/lib/security";
import { fhirBundle, fhirCode, fhirIdentifier, fhirReference } from "@/lib/domain/fhir";

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  const access = await requirePermission("patient:read"); if (access.response) return access.response;
  const user = access.user as any;
  const patient = await prisma.patient.findUnique({ where: { id: params.id }, include: { identifiers: { where: { active: true } }, allergies: true, problems: true, medicationStatements: true, immunizations: true, procedures: true, diagnosticObservations: true, visits: { orderBy: { createdAt: "desc" }, take: 100, include: { diagnoses: true } } } });
  if (!patient || !patient.active || patient.mergedIntoId || patient.organizationId !== user.organizationId) return NextResponse.json({ issue: [{ severity: "error", code: "not-found", diagnostics: "Patient not found" }], resourceType: "OperationOutcome" }, { status: 404, headers: { "Content-Type": "application/fhir+json" } });
  const subject = fhirReference("Patient", patient.id);
  const resources: any[] = [{ resourceType: "Patient", id: patient.id, active: patient.active, identifier: patient.identifiers.map(fhirIdentifier), name: [{ text: patient.name }], telecom: [patient.phone ? { system: "phone", value: patient.phone } : null, patient.email ? { system: "email", value: patient.email } : null].filter(Boolean), gender: patient.gender.toLowerCase(), birthDate: patient.dateOfBirth?.toISOString().slice(0, 10), address: patient.address ? [{ text: patient.address }] : undefined }];
  patient.allergies.forEach((item) => resources.push({ resourceType: "AllergyIntolerance", id: item.id, patient: subject, clinicalStatus: { coding: [{ system: "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical", code: item.clinicalStatus.toLowerCase().replaceAll("_", "-") }] }, verificationStatus: { coding: [{ system: "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification", code: item.verificationStatus.toLowerCase().replaceAll("_", "-") }] }, code: fhirCode(item.code, item.codingSystem, item.name), reaction: item.reaction ? [{ manifestation: [{ text: item.reaction }], severity: item.severity === "LIFE_THREATENING" ? "severe" : item.severity.toLowerCase() }] : undefined, onsetDateTime: item.onsetDate?.toISOString(), note: item.notes ? [{ text: item.notes }] : undefined }));
  patient.problems.forEach((item) => resources.push({ resourceType: "Condition", id: item.id, subject, clinicalStatus: { coding: [{ system: "http://terminology.hl7.org/CodeSystem/condition-clinical", code: item.clinicalStatus.toLowerCase().replaceAll("_", "-") }] }, verificationStatus: { coding: [{ system: "http://terminology.hl7.org/CodeSystem/condition-ver-status", code: item.verificationStatus.toLowerCase().replaceAll("_", "-") }] }, code: fhirCode(item.code, item.codingSystem, item.description), onsetDateTime: item.onsetDate?.toISOString(), abatementDateTime: item.resolvedDate?.toISOString(), note: item.notes ? [{ text: item.notes }] : undefined }));
  patient.medicationStatements.forEach((item) => resources.push({ resourceType: "MedicationStatement", id: item.id, subject, status: medicationStatus(item.status), medicationCodeableConcept: fhirCode(item.medicationCode, item.codingSystem, item.medication), effectivePeriod: item.effectiveFrom || item.effectiveTo ? { start: item.effectiveFrom?.toISOString(), end: item.effectiveTo?.toISOString() } : undefined, dosage: item.dose || item.frequency || item.route ? [{ text: [item.dose, item.dosageUnit, item.frequency, item.route].filter(Boolean).join(" ") }] : undefined, reasonCode: item.reason ? [{ text: item.reason }] : undefined, note: item.notes ? [{ text: item.notes }] : undefined }));
  patient.immunizations.forEach((item) => resources.push({ resourceType: "Immunization", id: item.id, patient: subject, status: item.status.toLowerCase(), vaccineCode: fhirCode(item.vaccineCode, item.codingSystem, item.vaccine), occurrenceDateTime: item.occurrenceDate.toISOString(), lotNumber: item.lotNumber || undefined, manufacturer: item.manufacturer ? { display: item.manufacturer } : undefined, site: item.site ? { text: item.site } : undefined, route: item.route ? { text: item.route } : undefined, note: item.notes ? [{ text: item.notes }] : undefined }));
  patient.procedures.forEach((item) => resources.push({ resourceType: "Procedure", id: item.id, subject, status: item.status.toLowerCase(), code: fhirCode(item.code, item.codingSystem, item.description), performedDateTime: item.performedAt?.toISOString(), performer: item.performer ? [{ actor: { display: item.performer } }] : undefined, bodySite: item.bodySite ? [{ text: item.bodySite }] : undefined, outcome: item.outcome ? { text: item.outcome } : undefined, note: item.notes ? [{ text: item.notes }] : undefined }));
  patient.diagnosticObservations.forEach((item) => resources.push({ resourceType: "Observation", id: item.id, subject, status: item.status.toLowerCase().replaceAll("_", "-"), code: fhirCode(item.code, item.codingSystem, item.display), effectiveDateTime: item.observedAt.toISOString(), valueQuantity: item.valueNumber != null ? { value: item.valueNumber, unit: item.unit || undefined, code: item.unitCode || undefined } : undefined, valueString: item.valueText || undefined, valueBoolean: item.valueBoolean ?? undefined, referenceRange: item.referenceLow != null || item.referenceHigh != null || item.referenceText ? [{ low: item.referenceLow != null ? { value: item.referenceLow, unit: item.unit || undefined } : undefined, high: item.referenceHigh != null ? { value: item.referenceHigh, unit: item.unit || undefined } : undefined, text: item.referenceText || undefined }] : undefined, interpretation: [{ text: item.interpretation }], note: item.isCritical ? [{ text: "Critical result" }] : undefined }));
  patient.visits.forEach((item) => {
    item.diagnoses.forEach((diagnosis) => resources.push({ resourceType: "Condition", id: diagnosis.id, subject, encounter: fhirReference("Encounter", item.id), clinicalStatus: diagnosis.clinicalStatus ? { text: diagnosis.clinicalStatus } : undefined, code: fhirCode(diagnosis.code, diagnosis.codingSystem, diagnosis.description) }));
    resources.push({ resourceType: "Encounter", id: item.id, subject, status: encounterStatus(item.status), period: { start: item.createdAt.toISOString(), end: item.signedAt?.toISOString() }, reasonCode: item.chiefComplaint ? [{ text: item.chiefComplaint }] : undefined, diagnosis: item.diagnoses.map((diagnosis) => ({ condition: fhirReference("Condition", diagnosis.id), use: diagnosis.isPrimary ? { text: "Primary" } : undefined })) });
  });
  await audit({ organizationId: patient.organizationId, userId: user.id, patientId: patient.id, action: "FHIR_PATIENT_EXPORT", resourceType: "FHIRBundle", resourceId: patient.id, request: req });
  return NextResponse.json(fhirBundle(resources), { headers: { "Content-Type": "application/fhir+json", "Content-Disposition": `attachment; filename="${patient.mrn}-fhir-bundle.json"` } });
}

function medicationStatus(status: string) { return ({ ACTIVE: "active", COMPLETED: "completed", ENTERED_IN_ERROR: "entered-in-error", INTENDED: "intended", STOPPED: "stopped", ON_HOLD: "on-hold", UNKNOWN: "unknown" } as Record<string, string>)[status] || "unknown"; }
function encounterStatus(status: string) { return ({ DRAFT: "planned", WAITING: "arrived", IN_PROGRESS: "in-progress", COMPLETED: "finished", FINALIZED: "finished", AMENDED: "finished", CANCELLED: "cancelled" } as Record<string, string>)[status] || "unknown"; }
