"use client";

import { useEffect, useState } from "react";
import { Activity, AlertTriangle, CalendarDays, CheckCircle2, ChevronDown, ChevronUp, FileText, HeartPulse, LogOut, Pill, Receipt, Stethoscope, TestTube2, UserRound } from "lucide-react";

export default function PatientJacketPage() {
  const [patient, setPatient] = useState<any>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/patient-portal").then(async (response) => { if (response.status === 401) { window.location.assign("/patient-login"); return; } const data = await response.json(); if (!response.ok) throw new Error(data.error); setPatient(data); }).catch((reason) => setError(reason.message || "Could not load your record.")); }, []);
  if (error) return <div className="rounded-xl bg-alertSoft p-4 text-alert">{error}</div>;
  if (!patient) return <div className="text-inkSoft">Loading your patient jacket…</div>;

  const nextAppointment = [...patient.appointments].filter((appointment: any) => appointment.status === "SCHEDULED" && new Date(appointment.scheduledAt) >= new Date()).sort((a: any, b: any) => +new Date(a.scheduledAt) - +new Date(b.scheduledAt))[0];
  return <div className="mx-auto max-w-5xl pb-10">
    <header className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent text-white"><HeartPulse size={20} /></span><div><p className="font-serif text-lg font-bold">EMR Patient Portal</p><p className="text-xs text-inkSoft">Private health record access</p></div></div><button onClick={async () => { await fetch("/api/patient-portal/logout", { method: "POST" }); window.location.assign("/patient-login"); }} className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-sm font-bold text-alert"><LogOut size={15} /> Sign out</button></header>
    <section className="overflow-hidden rounded-2xl bg-[#214F43] text-white shadow-xl shadow-[#214F43]/10"><div className="grid gap-6 p-6 sm:grid-cols-[1fr_auto] sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#BFD9CE]">Patient jacket</p><h1 className="mt-2 font-serif text-3xl font-bold">{patient.name}</h1><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-sm text-[#DDEBE5]"><span>{patient.mrn}</span><span>{patient.age} years · {patient.gender}</span><span>{patient.organization.name}</span></div></div><div className="flex items-center gap-3 rounded-xl bg-white/10 px-4 py-3"><HeartPulse size={28} className="text-[#F0B968]" /><div><p className="text-xs text-[#BFD9CE]">Blood group</p><p className="text-xl font-bold">{patient.bloodGroup || "Not recorded"}</p></div></div></div></section>

    {patient.allergies.length > 0 && <div className="mt-4 flex items-start gap-3 rounded-xl border border-[#E8B9A9] bg-alertSoft p-4 text-alert"><AlertTriangle size={19} className="mt-0.5 shrink-0" /><div><p className="font-bold">Allergy alert</p><p className="mt-1 text-sm">{patient.allergies.map((allergy: any) => allergy.name).join(", ")}</p></div></div>}

    <div className="mt-5 grid gap-4 md:grid-cols-3"><Summary icon={<Activity size={19} />} label="Completed visits" value={patient.visits.length} /><Summary icon={<CalendarDays size={19} />} label="Appointments" value={patient.appointments.length} /><Summary icon={<FileText size={19} />} label="Clinical documents" value={patient.visits.filter((visit: any) => visit.signedAt).length} /></div>

    {nextAppointment && <section className="mt-5 rounded-xl border border-[#C8DED4] bg-accentSoft p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-accentDark"><CalendarDays size={16} /> Next appointment</div><p className="mt-2 font-serif text-xl font-bold">{new Date(nextAppointment.scheduledAt).toLocaleString()}</p><p className="mt-1 text-sm text-inkSoft">{nextAppointment.doctor?.name ? `Dr. ${nextAppointment.doctor.name}` : "Doctor to be assigned"}{nextAppointment.reason ? ` · ${nextAppointment.reason}` : ""}</p></section>}

    <section className="mt-8"><SectionTitle icon={<UserRound size={18} />} title="My details" /><div className="mt-3 grid gap-3 rounded-xl border border-border bg-card p-5 text-sm sm:grid-cols-2 lg:grid-cols-3"><Detail label="Date of birth" value={patient.dateOfBirth ? new Date(patient.dateOfBirth).toLocaleDateString() : "Not recorded"} /><Detail label="Phone" value={patient.phone || "Not recorded"} /><Detail label="Email" value={patient.email || "Not recorded"} /><Detail label="Address" value={patient.address || "Not recorded"} /><Detail label="Emergency contact" value={patient.emergencyContact || "Not recorded"} /><Detail label="Member since" value={new Date(patient.createdAt).toLocaleDateString()} /></div></section>

    <section className="mt-8"><SectionTitle icon={<Stethoscope size={18} />} title="Health record history" /><div className="mt-3 space-y-3">{patient.visits.length === 0 ? <Empty text="No completed visits are available yet." /> : patient.visits.map((visit: any) => <VisitCard key={visit.id} visit={visit} />)}</div></section>

    <section className="mt-8"><SectionTitle icon={<Receipt size={18} />} title="Billing history" /><div className="mt-3 space-y-3">{patient.invoices.length === 0 ? <Empty text="No billing records are available." /> : patient.invoices.map((invoice: any) => <div key={invoice.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-4"><div><p className="font-bold">Invoice #{invoice.invoiceNo}</p><p className="text-xs text-inkSoft">{new Date(invoice.createdAt).toLocaleDateString()} · {invoice.items.length} item{invoice.items.length === 1 ? "" : "s"}</p></div><div className="text-right"><p className="font-mono font-bold">₹{(invoice.grandTotal / 100).toFixed(2)}</p><p className={`text-xs font-bold ${invoice.status === "PAID" ? "text-accentDark" : "text-waiting"}`}>{invoice.status.replaceAll("_", " ")}</p></div></div>)}</div></section>
  </div>;
}

function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-xl border border-border bg-card p-4"><div className="flex items-center gap-2 text-accentDark">{icon}<span className="text-xs font-bold uppercase tracking-wider text-inkSoft">{label}</span></div><p className="mt-3 font-serif text-3xl font-bold">{value}</p></div>; }
function SectionTitle({ icon, title }: { icon: React.ReactNode; title: string }) { return <h2 className="flex items-center gap-2 font-serif text-xl font-bold text-ink">{icon}{title}</h2>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-bold uppercase text-inkSoft">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-border p-6 text-center text-sm text-inkSoft">{text}</div>; }

function VisitCard({ visit }: { visit: any }) {
  const [open, setOpen] = useState(false);
  return <article className="overflow-hidden rounded-xl border border-border bg-card"><button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between gap-4 p-4 text-left"><div><div className="flex items-center gap-2"><CheckCircle2 size={16} className="text-accent" /><p className="font-bold">{visit.chiefComplaint || visit.diagnosis || "Clinical visit"}</p></div><p className="mt-1 text-xs text-inkSoft">{new Date(visit.createdAt).toLocaleString()}{visit.doctor?.name ? ` · Dr. ${visit.doctor.name}` : ""}</p></div>{open ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button>{open && <div className="border-t border-border bg-[#FAF8F2] p-4 text-sm"><div className="grid gap-3 sm:grid-cols-2"><Detail label="Diagnosis" value={visit.diagnosis || "Not recorded"} /><Detail label="Vitals" value={`BP ${visit.bp || "—"} · Temp ${visit.temperature || "—"}°F · Pulse ${visit.pulse || "—"} · Weight ${visit.weight || "—"}kg`} /></div>{visit.doctorNotes && <RecordBlock title="Doctor's notes" text={visit.doctorNotes} />}{visit.advice && <RecordBlock title="Advice" text={visit.advice} />}{visit.prescriptions.length > 0 && <div className="mt-4"><p className="flex items-center gap-2 font-bold"><Pill size={15} /> Prescriptions</p><ul className="mt-2 space-y-2">{visit.prescriptions.map((item: any) => <li key={item.id} className="rounded-lg bg-white p-3"><b>{item.medicine}</b><span className="text-inkSoft"> · {[item.dosage, item.frequency, item.duration].filter(Boolean).join(" · ")}</span></li>)}</ul></div>}{visit.testsOrdered.length > 0 && <div className="mt-4"><p className="flex items-center gap-2 font-bold"><TestTube2 size={15} /> Tests ordered</p><p className="mt-2 text-inkSoft">{visit.testsOrdered.map((test: any) => test.name).join(", ")}</p></div>}{visit.signedAt && <p className="mt-4 border-t border-dashed border-border pt-3 font-serif italic text-accentDark">Digitally signed{visit.doctor?.name ? ` by Dr. ${visit.doctor.name}` : ""} on {new Date(visit.signedAt).toLocaleString()}</p>}</div>}</article>;
}
function RecordBlock({ title, text }: { title: string; text: string }) { return <div className="mt-4"><p className="font-bold">{title}</p><p className="mt-1 whitespace-pre-wrap leading-6 text-inkSoft">{text}</p></div>; }
